name: CI/CD Azure

on:
  push:
    branches:
      - mestre

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t mateus169/todo-app:latest .

      - name: Push Docker Image
        run: docker push mateus169/todo-app:latest

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: tr123
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: mateus169/todo-app:latest
